setwd('/Users/m102324/Documents/my_code/epitimer/methylclock_rdat')


load("TestDataset.rda")
load("coefBlup.rda")
load("coefBohlin.rda")
load("coefEN.rda")
load("coefEPIC.rda")
load("coefHannum.rda")
load("coefHorvath.rda")
load("coefKnightGA.rda")
load("coefLeeGA.rda")
load("coefLevine.rda")
load("coefMayneGA.rda")
load("coefPedBE.rda")
load("coefSkin.rda")
load("coefTL.rda")
load("coefWu.rda")
load("cpgs.bn.rda")
load("probeAnnotation21kdatMethUsed.rda")
load("progress_data.rda")
load("progress_vars.rda")
load("references.rda")

write.table(TestDataset, file="TestDataset.tsv", quote=F, sep="\t")
write.table(coefBlup, file="coefBlup.tsv", quote=F, sep="\t")
write.table(coefBohlin, file="coefBohlin.tsv", quote=F, sep="\t")
write.table(coefEN, file="coefEN.tsv", quote=F, sep="\t")
write.table(coefEPIC, file="coefEPIC.tsv", quote=F, sep="\t")
write.table(coefHannum, file="coefHannum.tsv", quote=F, sep="\t")
write.table(coefHorvath, file="coefHorvath.tsv", quote=F, sep="\t")
write.table(coefKnightGA, file="coefKnightGA.tsv", quote=F, sep="\t")
write.table(coefLeeGA, file="coefLeeGA.tsv", quote=F, sep="\t")
write.table(coefLevine, file="coefLevine.tsv", quote=F, sep="\t")
write.table(coefMayneGA, file="coefMayneGA.tsv", quote=F, sep="\t")
write.table(coefPedBE, file="coefPedBE.tsv", quote=F, sep="\t")
write.table(coefSkin, file="coefSkin.tsv", quote=F, sep="\t")
write.table(coefTL, file="coefTL.tsv", quote=F, sep="\t")
write.table(coefWu, file="coefWu.tsv", quote=F, sep="\t")
write.table(cpgs.bn, file="cpgs.bn.tsv", quote=F, sep="\t")
write.table(probeAnnotation21kdatMethUsed, file="probeAnnotation21kdatMethUsed.tsv", quote=F, sep="\t")
write.table(progress_data, file="progress_data.tsv", quote=F, sep="\t")
write.table(progress_vars, file="progress_vars.tsv", quote=F, sep="\t")
#write.table(references, file="references.tsv", quote=F, sep="\t")

